version: '3.8'
services:
  db-star-wars:
    container_name: nestjs-star-wars
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - conexa
  test-db-star-wars:
    container_name: nestjs-star-wars-test-db
    image: postgres:latest
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - conexa
networks:
  conexa:
