-- AlterTable
ALTER TABLE "Movie" ALTER COLUMN "url" DROP NOT NULL,
ALTER COLUMN "characters" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "planets" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "species" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "starships" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "vehicles" SET DEFAULT ARRAY[]::TEXT[];
